// Automatically generated by flapigen
package com.keystone.cold.lib;
import androidx.annotation.NonNull;

public final class KeystoneSigner {

    public KeystoneSigner() {
        mNativeObj = init();
    }
    private static native long init();

    public final @NonNull String processCommand(@NonNull String command_string) {
        String ret = do_processCommand(mNativeObj, command_string);

        return ret;
    }
    private static native @NonNull String do_processCommand(long self, @NonNull String command_string);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ KeystoneSigner(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}